### ISSUE TITLE
updating to version 2.1.1

### ISSUE THREAD

**Issue by lukaszgit** [ucr-hpcc/hpcc_slurm_examples#2]
Hi, ver. 2.1.1 is installed on disc but run_alphafold_cle.sh included here still runs ver. 2.0.0. It would be nice to have it fully updated as version 2.0.0 has a bug (does not include local confidence in the output pub files), it seems. Otherwise it all works smoothly.
best

**Comment by jdhayes** [comment]
Hello, thanks for the information.
I have updated the script to reflect the lasted installed version of alphafold.
However, these are merely examples and the user can determine which version to load based on individual needs.

**Comment by lukaszgit** [comment]
Yes, of course I was able to modify the example script.

(note that at least two command lines of alphafold were changed in 2.1.1
and, I think, they have to be removed from the example script to be able to run it.)

The difference between 2.0.0 and 2.1.1 is important because
2.0.0 does not write local model's confidence score into output pdb files.

anyway, thanks for making it available

best

Lukasz

**Comment by jdhayes** [comment]
The original example was provided by a user.
If you would like to update this example, then I would welcome a PR :)

**Comment by lukaszgit** [comment]
Oh thanks I did not know that 😊

I will sent a working one for 2.1.1

Lukasz
